# Using version 2 as 3 does not support resource constraint options (cpu_*, mem_* limits) for non swarm mode in Compose
version: "2"

services:
    alfresco:
        build:
          context: ./alfresco
          args:
            ALFRESCO_TAG: ${ALFRESCO_TAG}
        mem_limit: 4g
        environment:
            JAVA_OPTS: "
                -Ddb.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
                -Ddb.username=SA
                -Ddb.password=Password1
                -Ddb.url=\"jdbc:sqlserver://${LOCAL_IP}:1433;databaseName=ILCLONEDALFDB01A;user=SA;password=Password1;lockTimeout=1000\"
                -Ddb.txn.isolation=4096
                -Ddb.pool.max=275
                -Dsolr.host=solr6
                -Dsolr.port.ssl=8983
                -Dsolr.secureComms=none
                -Dsolr.baseUrl=/solr
                -Dindex.subsystem.name=solr6
                -Dmessaging.subsystem.autoStart=false
                -Ddeployment.method=DOCKER_COMPOSE
                -Dtransform.service.enabled=false
                -Dlocal.transform.service.enabled=false
                -Dlegacy.transform.service.enabled=false
                -Dcsrf.filter.enabled=false
                -Dalfresco.restApi.basicAuthScheme=true
                -Xms3500m -Xmx3500m
                "
        ports:
            - 8080:8080
        volumes:
            - ./data/alf-repo-data:/usr/local/tomcat/alf_data

    solr6:
        build:
          context: ./search
          args:
            SEARCH_TAG: ${SEARCH_TAG}
            SOLR_HOSTNAME: solr6
            ALFRESCO_HOSTNAME: alfresco
            ALFRESCO_COMMS: none
            SEARCH_LOG_LEVEL: WARN
        mem_limit: 10g
        environment:
            #Solr needs to know how to register itself with Alfresco
            SOLR_ALFRESCO_HOST: "alfresco"
            SOLR_ALFRESCO_PORT: "8080"
            ALFRESCO_SECURE_COMMS: none
            #Alfresco needs to know how to call solr
            SOLR_SOLR_HOST: "solr6"
            SOLR_SOLR_PORT: "8983"
            #Create the default alfresco and archive cores
            SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco"
            SOLR_JAVA_MEM: "-Xms9216m -Xmx9216m"
            SOLR_OPTS: "
               -agentpath:/usr/local/YourKit-JavaProfiler-2019.8/bin/linux-x86-64/libyjpagent.so=port=10001,listen=all
            "
            # Java 11 GC settings
            GC_TUNE: "
                -XX:+UseG1GC
                -XX:+PerfDisableSharedMem
                -XX:+ParallelRefProcEnabled
                -XX:G1HeapRegionSize=8m
                -XX:MaxGCPauseMillis=250
                -XX:InitiatingHeapOccupancyPercent=75
                -XX:+UseLargePages
                -XX:+AggressiveOpts
              "
        ports:
            - 8083:8983
            - 10001:10001
